Repository neoave/mrack, pull requests merged in 2023-03, with the labels that each got.

#250 refactor: Update supported providers
  README.md
Labels: documentation, trivial

#251 fix(OpenStack): Add missing await for self._load_limits() method call
  src/mrack/providers/openstack.py
Labels: bug, review needed, trivial

#252 refactor(AWS): change variable name typo in get_ip_addresses
  src/mrack/providers/aws.py
Labels: trivial

#253 fix: Replace coroutines with tasks to avoid RuntimeError
  src/mrack/providers/openstack.py
  tests/unit/test_openstack.py
Labels: unexpected behavior

#254 fix: empty the success hosts and correctly set missing_reqs
  src/mrack/providers/provider.py
Labels: bug
